browgames/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/<int:game_id>/', views.games_detail, name="detail"),
    path('games/create/', views.GameCreate.as_view(), name='games_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='games_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='games_delete'),
    path('games/<int:game_id>/add_comment/', views.add_comment, name='add_comment'),
    path('games/<int:game_id>/add_photo/', views.add_photo, name='add_photo'),
    path('games/<int:game_id>/assoc_genre/<int:genre_id>/', views.assoc_genre, name='assoc_genre'),
    path('games/<int:game_id>/comment_update/<int:comment_id>/', views.CommentUpdate.as_view(), name='comment_update'),
    path('games/<int:game_id>/comment_delete/<int:comment_id>/', views.CommentDelete.as_view(), name='comment_delete'),
    path('genres/', views.GenreList.as_view(), name='genres_index'),
    path('genres/create/', views.GenreCreate.as_view(), name='genres_create'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profiles/', views.profiles_index, name='profile_index'),
    path('profiles/create/', views.ProfileCreate.as_view(), name="profile_create"),
    path('profiles/<int:profile_id>/', views.profile_detail, name='profile_detail'),
    path('profiles/<int:pk>/update/', views.ProfileUpdate.as_view(), name="profile_update"),
    path('profiles/<int:pk>/delete/', views.ProfileDelete.as_view(), name="profile_delete"),
]

main_app/models.py
from django.db import models
from django.forms import CharField
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

RATINGS = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
)

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('genres_detail', kwargs={'pk': self.id})

class Game(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    link = models.CharField(max_length=1000)
    creator = models.CharField(max_length=50)
    
    genres = models.ManyToManyField(Genre)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})

class Comment(models.Model):
    rating = models.IntegerField(
        choices=RATINGS,
        default=RATINGS[0][0])
    comment = models.TextField(max_length=1000)

    game = models.ForeignKey(Game, on_delete=models.CASCADE)
   

    def __str__(self):
        return f"Rating: {self.get_rating_display()} Comment: {self.comment}"

class Profile(models.Model):
    username = models.CharField(max_length=100)
    contact_info = models.TextField(max_length=1000)
    bio = models.TextField(max_length=1500)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #games = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('detail', kwargs={'profile_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    # profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for game_id: {self.game_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['rating', 'comment']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from . models import Game, Genre, Comment, Photo, Profile
from .forms import CommentForm
from django.db.models.signals import post_save
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os
import uuid
import boto3


# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def games_index(request):
  games = Game.objects.all()
  return render(request, 'games/index.html', { 'games': games })

@login_required
def games_detail(request, game_id):
  game = Game.objects.get(id=game_id)
  id_list = game.genres.all().values_list('id')
  genres_game_doesnt_have = Genre.objects.exclude(id__in=id_list)
  comment_form = CommentForm()
  print(genres_game_doesnt_have)
  return render(request, 'games/detail.html', {
    'game': game,
    'comment_form': comment_form,
    'genres': genres_game_doesnt_have
  })

def assoc_genre(request, game_id, genre_id):
  Game.objects.get(id=game_id).genres.add(genre_id)
  return redirect('detail', game_id=game_id)

class GameCreate(LoginRequiredMixin, CreateView):
  model = Game
  fields = ['title', 'description', 'link', 'creator']
  success_url = '/games/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class GameUpdate(LoginRequiredMixin, UpdateView):
  model = Game
  fields = ['title', 'description', 'link', 'creator']
  
class GameDelete(LoginRequiredMixin, DeleteView):
  model = Game
  success_url = '/games/'
  
@login_required
def add_comment(request, game_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.game_id = game_id
        new_comment.save()
    return redirect('detail', game_id=game_id)

class CommentUpdate(LoginRequiredMixin, UpdateView):
  model = Comment
  fields = '__all__'

class CommentDelete(LoginRequiredMixin, DeleteView):
  model = Comment
  success_url = '/games/'

class GenreList(LoginRequiredMixin, ListView):
    model = Genre

class GenreCreate(LoginRequiredMixin, CreateView):
    model = Genre
    fields = '__all__'
    success_url = '/genres/'

def profiles_index(request):
  profiles = Profile.objects.all()
  return render(request, 'profiles/index.html', { 'profiles': profiles })

def profile_detail(request, profile_id):
  profile = Profile.objects.get(id=profile_id)
  return render(request, 'profiles/detail.html', { 'profile': profile })
  
class ProfileCreate(LoginRequiredMixin, CreateView):
  model = Profile
  fields = ['username', 'bio', 'contact_info']
  success_url = '/profiles/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class ProfileUpdate(LoginRequiredMixin, UpdateView):
  model = Profile
  fields = ['username', 'bio', 'contact_info']
  success_url = '/profiles/'

class ProfileDelete(LoginRequiredMixin, DeleteView):
  model = Profile
  success_url = '/profiles/'

@login_required
def add_photo(request, game_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, game_id=game_id)
    except Exception as e:
      print('An error occured uploading file to S3')
      print(e)
  return redirect('detail', game_id=game_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('profile_create')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<br />
<h1>Brow Game</h1>
<br />
<hr />
<h3>What is Brow Games about?</h3>
<hr />
<p>Brow Games was made for Creators to share their Web Browser Games with other Creators and Gamers.<br />
    We wanted some where that people can come together, share their games, let others play them and rate the games themselves.<br />
    We hope to see you around and either uploading some cool games or playing them!
    <br /><br />
    Happy Gaming!
    <br /><br />
    - Brow Game Team
</p>
<hr />
<h3>Credits</h3>
<hr />
lamekammi<br />
Alex Azevedo<br />
Jacob Shapiro

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Brow Games</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
  <nav style="background-color: lightslategrey;">
    <div class="nav-wrapper">
      <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo"><img src='https://i.imgur.com/wu8lZCE.png?2' alt='Mini Brow Games Logo'></a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'genres_create' %}">Add Genre</a></li>
          <li><a href="{% url 'genres_index' %}">Genres</a></li>
          <li><a href="{% url 'games_create' %}">Add Game</a></li>
          <li><a href="/games">Games</a></li>
          <li><a href="/profiles">Profiles</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer" style="background-color: lightslategrey;">
    <div class="right">All Rights Reserved, &copy; 2022 Brow Games &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% block content %}

<br />
<h1>{{ game.title }}</h1>
<br />
  <div class="card-action">
    {% for photo in game.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}" width="600" height="600">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    {% if user.id == game.user_id %}
      <form action="{% url 'add_photo' game.id %}" enctype="multipart/form-data" method="POST" alt="Game Photo" class="card-panel">
        {% csrf_token %}
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Upload Photo">
      </form>
    {% endif %}
  </div>
  <div class="card">
    <div class="card-content">
      <h5>Description:</h5> 
      <p>{{ game.description }}</p>
      <h5>Creator:</h5> 
      <p>{{ game.creator }}</p>
      <br />
      <button class="play"><a class="play-link" href=" {{ game.link }} " target="_blank"><img src="https://i.imgur.com/oZjkKDd.png?1" alt="Play" class="play-now"></a>
    </div>
    <div class="card-action">
      {% if user.id == game.user_id %}
        <a href="{% url 'games_update' game.id %}">Edit</a>
        <a href="{% url 'games_delete' game.id %}">Delete</a>
      {% endif %}
    </div>
  </div>
  <br />
    <form action="{% url 'add_comment' game.id %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" class="btn" value="Add Comment">
    </form>
  <br />
  <hr />
    {% for comment in game.comment_set.all %}
      <h5>Rating:</h5>
      <p> {{ comment.rating }}</p>
      <h5>Comment:</h5> 
      <p>{{ comment.comment }}</p>
      <hr />
    {% endfor %}
    <br />
    <h3>{{ game.title }}'s Genres</h3>
      {% if game.genres.count %}
        {% for genre in game.genres.all %}
          <span class="card-title">
            {{ genre.name }}
            <br />
          </span>
        {% endfor %}
      {% else %}
        <h5>No Genres :(</h5>
      {% endif %}
    <br />
{% if user.id == game.user_id %}
  <h3>Available Genres</h3>
  {% if genres.count %}
      {% for genre in genres.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ genre.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_genre' game.id genre.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{game.title}} Already Has All Genres Available</h5>
    {% endif %}
  {% endif %}
<script>

  const selectEl = document.getElementById('id_rating');
  M.FormSelect.init(selectEl);
    
</script>
{% endblock %}
  

main_app/templates/games/index.html
{% extends 'base.html' %}
{% block content %}

<br />
<h1>Game List</h1>
<br />
{% for game in games %}
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ game.title }}</span>
    <p>{{ game.description }}</p>
    <a class="btn stretched-link white-text" href="{% url 'detail' game.id %}">Details</a>
  </div>
</div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<img src="https://i.imgur.com/fnsWI3G.png?2" alt="Brow Games Logo" class="logo">

{% endblock %}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<br />
  <h1>Delete Game</h1>
  <br />
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' game.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}
<br />
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.title}}</span></h1>
  {% else %}
    <h1>Add Game</h1>
  {% endif %}
  <br />
    <form action="" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/genre_form.html
{% extends 'base.html' %}

{% block content %}
<br />
    <h1>Add Genre</h1>
    <br />
  <form action="" method="post"> 
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>

{% endblock %}

main_app/templates/main_app/genre_list.html
{% extends 'base.html' %}
{% block content %}
<br />
<h1>Genre List</h1>
<br />
{% for genre in genre_list %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ genre.name }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/profile_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<br />
  <h1>Delete Profile</h1>
  <br />
  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'profile_detail' profile.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}

{% block content %}
<br />
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Profile</h1>
  {% endif %}
  <br />
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/profiles/detail.html
{% extends 'base.html' %}
{% block content %}

<br />
    <h1>{{ profile.username }}</h1>
    <hr />
    <br />
    <div class="card">
        <div class="card-content">
            <h5>Contact:</h5>
            <p>{{ profile.contact_info }}</p>
            <h5>Bio:</h5>
            <p>{{ profile.bio }}</p>
        </div>
        {% if user.id == profile.user_id %}
        <div class="card-action">
            <a href="{% url 'profile_update' profile.id %}">Edit</a>
            <a href="{% url 'profile_delete' profile.id %}">Delete</a>
        </div>
    </div>
    {% endif %}


{% endblock %}

main_app/templates/profiles/index.html
{% extends 'base.html' %}
{% block content %}
<br />
<h1>Profiles</h1>
<br />
{% for profile in profiles %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ profile.username }}</span>
            <p>{{ profile.bio }}</p>
            <a class="btn stretched-link white-text" href="{% url 'profile_detail' profile.id %}">Details</a>
        </div>
    </div>
{% endfor %}

{% endblock %}